apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elk-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01a1e7f4a4ba08ce2
  directoryPerms: "700"
  accessPointId: fsap-09d44b0e2ae7c9f42  
