apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-logstash-logs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elk-efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01a1e7f4a4ba08ce2::fsap-09d44b0e2ae7c9f42 
