apiVersion: logstash.k8s.elastic.co/v1alpha1  
kind: Logstash  
metadata:  
  name: logstash  
spec:  
  count: 1  
  version: 8.15.0  
  elasticsearchRefs:  
    - clusterName: eck  
      name: elasticsearch  
  pipelines:  
    - pipeline.id: main  
      config.string: |  
        input {  
          beats {  
            port => 5044  
          }  
        }  
        filter {  
          grok {  
            match => { "message" => "%{HTTPD_COMMONLOG}"}  
          }  
          geoip {  
            source => "[source][address]"  
            target => "[source]"  
          }  
        }  
        output {  
          if [apimMetrics] == "apim:response" {  
            elasticsearch {  
              index => "apim_event_response"  
              hosts => [ "${ECK_ES_HOSTS}" ]  
              user => "${ECK_ES_USER}"  
              password => "${ECK_ES_PASSWORD}"
              ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"  
            }  
          } else if [apimMetrics] == "apim:faulty" {  
            elasticsearch {  
              index => "apim_event_faulty"  
              hosts => [ "${ECK_ES_HOSTS}" ]  
              user => "${ECK_ES_USER}"  
              password => "${ECK_ES_PASSWORD}"
              ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
            }  
          } else {  
            elasticsearch {  
              index => "log"  
              hosts => [ "${ECK_ES_HOSTS}" ]  
              user => "${ECK_ES_USER}"  
              password => "${ECK_ES_PASSWORD}"
              ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
            }  
          }  
        }  
  services:  
    - name: beats  
      service:  
        spec:  
          type: ClusterIP  
          ports:  
            - port: 5044  
              name: "filebeat"  
              protocol: TCP  
              targetPort: 5044  