apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wild-crt
spec:
  secretName: wild-tls
  dnsNames:
  - "*.tsandev.org"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
