apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-crt
spec:
  secretName: elastic-tls
  dnsNames:
  - elastic.tsandev.org
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
