apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-crt
spec:
  secretName: kibana-tls
  dnsNames:
  - kibana.tsandev.org
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
