apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: websub-crt
spec:
  secretName: websub-tls
  dnsNames:
  - websub.tsandev.org
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
