apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: toesan@tsan.com
    privateKeySecretRef:
      name: letsencrypt-wildcard-key
    solvers:
    - dns01:
        cloudflare:
          email: toesan@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
